version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: "npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: unit-test
          command: "npm run test:coverage"
      - run:
          name: linting
          command: "npm run lint"
workflows:
  version: 2
  build:
    jobs:
      - test
